services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-dev-app}
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3420:3000"
    privileged: true
    shm_size: 4g
    restart: unless-stopped
    entrypoint: bash -c "next dev"
    working_dir: /app
