
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME:-dev}
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "2375:2375"
    privileged: true
    shm_size: 4g
    restart: unless-stopped
    network_mode: host
