
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - COMMUNE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    image: commune
    volumes:
      - ./api:/api/api
    working_dir: /api
    command: python api/api.py
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
